### PR TITLE
Add alt.conf theme from Geany

### PR DESCRIPTION
**Pull request by techee**
This PR adds the "alt" theme that is (currently) the only theme distributed with Geany. If https://github.com/geany/geany/pull/4044 gets merged to Geany, it makes more sense to have the main "home" of the "alt" theme in geany-plugins so when some global changes are made to all themes, the "alt" theme doesn't have to be updated separately.

Now the question is what license should the "alt" theme have? There's no explicit license right now. Should it be GPL 2 or later like Geany or something more permissive like MIT?

TODO: also add screenshot.

### CODE REVIEW

**Comment by eht16** [comment]
The "alt" theme was added in https://github.com/geany/geany/commit/c9f7afaf3a338a04fefca61cda5afef539bb7c33 by Nick directly in the Geany repository and so it should be GPLv2 or later as Geany itself.

**Comment by eht16** [comment]
`mkindex.py` works with Python3 (after some modifications a few months ago), to be called via "make index".

Anyway, I can do this after merging as well.

**Review by dmaphy — APPROVED** [review]

**Comment by techee** [comment]
> mkindex.py works with Python3 (after some modifications a few months ago), to be called via "make index".

OK, I was confused by
```
Note: requires Python Imaging Library (PIL), ex. 'python-imaging' Debian package.

# TODO this script needs to be ported to Python 3 properly
```
in the script and the fact that I didn't find the `python-imaging` package - it's probably renamed to something else now.

> Anyway, I can do this after merging as well.

Good, merged. I'll make it your problem now :-).

**Comment by eht16** [comment]
> > mkindex.py works with Python3 (after some modifications a few months ago), to be called via "make index".
> 
> OK, I was confused by
> 
> ```
> Note: requires Python Imaging Library (PIL), ex. 'python-imaging' Debian package.
> 
> # TODO this script needs to be ported to Python 3 properly
> ```
> 
> in the script and the fact that I didn't find the `python-imaging` package - it's probably renamed to something else now.

It's probably https://packages.debian.org/bookworm/python3-pil.
And the unclear comment is probably from me, I think to remember that I touched this script to make it run with Python3 but stopped at the point when it ran and thought this should be done better later.

> > Anyway, I can do this after merging as well.
> 
> Good, merged. I'll make it your problem now :-).

"Thanks" :). Problem solved.

**Pull request merged**
