### PR TITLE
[RFC] Add port of IntelliJ Darcula theme

### PR DESCRIPTION
**Pull request by techee**
Not a real pull request yet, just a RFC so far. I'm aware there's missing screenshot and the rest described in ADDING-A-THEME and right now the metadata at the beginning of the theme is incorrect.

The main question I'd like to ask is what license text I should use and what should contain the Author entry. I've based the theme on the Darcula theme which is the default dark theme used by IntelliJ products such as IntelliJ Idea or Android Studio. I created the theme basically from scratch and even had to use color picker to get the colors because there's apparently some alpha being used and the colors in the theme definition don't correspond to what's displayed. Should the author be IntelliJ, me or something else? And what license should be used?

Apart from that, does the theme look alright to you?

### CODE REVIEW

**Comment by elextr** [comment]
IANAL but I understand you should be able to use any license you want, it is not possible to copyright a set of colours, only the actual theme file, and basing your theme on the colours from the theme for another program does not copy or derive from that work, since you used no substantial portion of their theme file.  Your theme file is a different work in a different language, you are the author and copyright owner.  It would of course be nice to acknowledge the original theme in the description.

So your current template header needs replacing :)

Most themes seem to use GPL2+, so its probably good to be consistent.

**Comment by codebrainz** [comment]
Yeah probably best to use GPL just to make it easier on packagers. It would probably be good just in the comment at the start to put "Ported from the IntelliJ Darcula theme by Jiří Techet" or something so there's no ambiguity that it's based on that theme.

**Comment by codebrainz** [comment]
It looks ok at a quick glance, except this part: https://github.com/techee/geany-themes/commit/b1e7da64cb2744cf3fadd56f85bec797f2100aba#diff-b113132fa3229754d79091c5bab9b321R19

**Comment by techee** [comment]
OK, here's the real pull request, I hope I haven't forgotten anything.

**Comment by techee** [comment]
@codebrainz Ping

**Comment by techee** [comment]
By the way, what's the official geany-themes repository:

https://github.com/geany/geany-themes

or

https://github.com/codebrainz/geany-themes

The latter has a lot more stars but it can be because of historical reasons I guess.

**Comment by codebrainz** [comment]
@techee sorry, I haven't got to it yet, will try to do soon (or if you have the access, and want to do, feel free). Don't hesitate to ping again if I forget. There's a couple more I need to get merged in too here: https://github.com/codebrainz/geany-themes/pulls

The reason for the two repos is that I wanted to make it be "more official" by putting on the Geany organization, but I didn't want to break blog links and such stuff that points to the one under my user, so whenever I do updates, I just push to both remotes.

**Comment by codebrainz** [comment]
Added in e563131ae9527412bd7a301e05ff9dca0b651d44. Thanks!

**Pull request closed without merging**
