### PR TITLE
Add epsilon color scheme

### PR DESCRIPTION
**Pull request by N3mesis98**

### CODE REVIEW

**Comment by elextr** [comment]
Maybe needs a name change, a quick google shows there is a commercial wordpress theme also called esilon.

**Comment by N3mesis98** [comment]
Oh, I was not aware that this could cause some problems.
I will rename the theme to gEpsilon to avoid this clash...

**Comment by codebrainz** [comment]
There is no problem naming something with the same common word as something completely else. If there were, we'd have a lot more problems with other theme names than Epsilon.

**Comment by elextr** [comment]
Maybe I wasn't clear about the concern, it is not that Epsilon is a common
word, it is that it is the name of a commercial theme for another tool.

If this theme has a similar "look and feel" and is named after a commercial
theme, even if its for another tool, then the owner of that theme may feel
they need to protect their "property".

It depends how they approach it, but a takedown request could conceivably
see the whole Geany organisation removed from Github.

**Comment by codebrainz** [comment]
@elextr yeah I got it, I just don't think it's an issue. A website theme and syntax colour scheme are almost completely different things, except they both use colours.

If you want to pick nits, there are far "worse" "issues" of "property" in geany-themes. For example the Github theme uses the Github name (probably trademarked) as well as intentionally uses colours inspired by their source code highlighting scheme. Similarly the Ubuntu theme uses the Ubuntu name (probably trademarked) as well as using the theme colours from their product.

I think any of this is a complete non-issue that adding a `g` prefix won't affect. Let's leave lawyering for lawyers :)

**Comment by elextr** [comment]
>  Github name (probably trademarked) as well as intentionally uses colours inspired by their source code highlighting scheme.

Indeed, "The look and feel of the Service is copyright © GitHub, Inc. All rights reserved. You may not duplicate, copy, or reuse any portion of the HTML/CSS, Javascript, or _visual design elements_ or concepts without express written permission from GitHub." (my emphasis)

Ubuntu is likely similar, but it changes its theme often enough that it might have some trouble enforcing it.

Agree adding a `g` won't help :)

It appears that github will remove the repository thats subject to a takedown on [24 hours notice](https://help.github.com/articles/dmca-takedown-policy/), not the entire organisation.  Since thats only the themes its not so bad.

**Comment by N3mesis98** [comment]
I will remove that last commit then.

**Comment by N3mesis98** [comment]
So, the pull request is lying in this state for quite some time now.
Is there something I must change for this theme to be accepted ?

**Comment by codebrainz** [comment]
No, it looks quite good, I just haven't gotten around to testing it and merging the PR yet.

**Pull request closed without merging**
